#ifndef USER_MANAGMENT_USER_HANDLING_CFG_H_
#define USER_MANAGMENT_USER_HANDLING_CFG_H_

#define MAX_NUMBER_OF_USERS		10

#define USER_NAME_MAX_SIZE		10
#define USER_PASS_MAX_SIZE		10


//  USER_ONE_NAME_ADD		0x00

//  USER_ONE_PASS_ADD		0x18

#endif /* USER_MANAGMENT_USER_HANDLING_CFG_H_ */
